export default {
  ADMIN: ["ADMIN"],
  MANAGER: ["ADMIN", "MANAGER"],
  TECH: ["ADMIN", "MANAGER", "TECH"],
  CUSTOMER: ["ADMIN", "MANAGER", "TECH", "CUSTOMER"],
  ALL: ["ADMIN", "MANAGER", "TECH", "CUSTOMER"],
};
