export default {
  ADMIN: ["ADMIN", "MANAGER", "TECH", "CUSTOMER"],
  MANAGER: ["MANAGER", "TECH", "CUSTOMER"],
  TECH: ["TECH", "CUSTOMER"],
  CUSTOMER: ["CUSTOMER"],
  ALL: ["ADMIN", "MANAGER", "TECH", "CUSTOMER"],
};
